/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 23-янв-2024 9:22:20 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS permission CASCADE;

DROP TABLE IF EXISTS product CASCADE;

DROP TABLE IF EXISTS role CASCADE;

DROP TABLE IF EXISTS role_permissions CASCADE;

DROP TABLE IF EXISTS user_product_ext CASCADE;

DROP TABLE IF EXISTS user_profile CASCADE;

DROP TABLE IF EXISTS user_roles CASCADE;

/* Create Tables */

CREATE TABLE permission
(
    id integer NOT NULL,	-- Уникальный идентификатор разрешения
    name varchar(80) NOT NULL,	-- Имя разрешения
    descr varchar(255) NULL,	-- Описание разрешения
    alias varchar(50) NOT NULL,	-- Алиас разрешения для enum внутри java кода
    deleted boolean NULL   DEFAULT false	-- Признак удаленного разрешения (физически строки из таблицы не  удаляем, проставляем этот признак)
);

CREATE TABLE product
(
    id_product_ext integer NOT NULL,	-- Внешний идентификатор продукта из MyProduct
    name varchar(250) NOT NULL,	-- Имя продукта
    alias varchar(50) NOT NULL	-- Алиас (код) продукта
);

CREATE TABLE role
(
    id integer NOT NULL,	-- Уникальный идентификатор роли
    name varchar(80) NOT NULL,	-- Имя роли
    descr varchar(255) NULL,	-- Описание роли
    alias varchar(50) NOT NULL,	-- Алиас роли для enum в Java
    deleted boolean NULL   DEFAULT false	-- Признак удаленной роли. Строки в таблице не удаляем, помечаем признаком.
);

CREATE TABLE role_permissions
(
    id_rec integer NOT NULL,	-- идентификатор записи, первичный ключ
    id_permission integer NOT NULL,	-- идентификатор разрешения
    b_set boolean NOT NULL,	-- флаг установки пермишена
    id_role integer NOT NULL	-- Идентификатор роли
);

CREATE TABLE user_product_ext
(
    id_rec integer NOT NULL,	-- идентификатор записи, первичный ключ
    id_profile integer NULL,	-- идентификатор пользователя,, внешний ключ
    id_product_ext integer NULL	-- Идентификатор продукта, внешний ключ
);

CREATE TABLE user_profile
(
    id integer NOT NULL,	-- Идентификатор пользователя внутренний
    id_ext varchar(50) NOT NULL,	-- Идентификатор пользователя внешний, табельный номер
    full_name varchar(255) NOT NULL,	-- Полное имя (ФИО)
    login varchar(50) NOT NULL,	-- учетная запись, логин из AD
    last_login timestamp without time zone NULL,	-- Дата последнего входа в систему
    email varchar(100) NOT NULL	-- E-mail пользователя
);

CREATE TABLE user_roles
(
    id_rec integer NOT NULL,	-- Идентификатор записи, первичный ключ
    id_profile integer NULL,	-- Идентификатор профиля, внешний ключ
    id_role integer NULL	-- Идентификтаор внутренней роли, внешний ключ
);

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE permission ADD CONSTRAINT "PK_Permission"
    PRIMARY KEY (id);

ALTER TABLE permission
    ADD CONSTRAINT "UI_Premission_Alias" UNIQUE (alias);

ALTER TABLE product ADD CONSTRAINT "PK_Product"
    PRIMARY KEY (id_product_ext);

ALTER TABLE role ADD CONSTRAINT "PK_Role"
    PRIMARY KEY (id)
;

ALTER TABLE role
    ADD CONSTRAINT "UI_Role_Name" UNIQUE (name);

ALTER TABLE role_permissions ADD CONSTRAINT "PK_RolePermissions"
    PRIMARY KEY (id_rec);

CREATE INDEX "IXFK_RolePermissions_Permission" ON role_permissions (id_permission ASC);

CREATE INDEX "IXFK_RolePermissions_Role" ON role_permissions (id_role ASC);

ALTER TABLE user_product_ext ADD CONSTRAINT "PK_UserProductRolesExt"
    PRIMARY KEY (id_rec);

CREATE INDEX "IXFK_UserProductRolesExt_Product" ON user_product_ext (id_product_ext ASC);

CREATE INDEX "IXFK_UserProductRolesExt_UserProfile" ON user_product_ext (id_profile ASC);

ALTER TABLE user_profile ADD CONSTRAINT "PK_UserProfile"
    PRIMARY KEY (id);

ALTER TABLE user_profile
    ADD CONSTRAINT "uniqLogin" UNIQUE (login);

ALTER TABLE user_roles ADD CONSTRAINT "PK_UserRoles"
    PRIMARY KEY (id_rec);

CREATE INDEX "IXFK_UserRoles_Role" ON user_roles (id_role ASC);

CREATE INDEX "IXFK_UserRoles_UserProfile" ON user_roles (id_profile ASC);

/* Create Foreign Key Constraints */

ALTER TABLE role_permissions ADD CONSTRAINT "FK_RolePermissions_Permission"
    FOREIGN KEY (id_permission) REFERENCES permission (id) ON DELETE No Action ON UPDATE No Action;

ALTER TABLE role_permissions ADD CONSTRAINT "FK_RolePermissions_Role"
    FOREIGN KEY (id_role) REFERENCES role (id) ON DELETE No Action ON UPDATE No Action;

ALTER TABLE user_product_ext ADD CONSTRAINT "FK_UserProductRolesExt_Product"
    FOREIGN KEY (id_product_ext) REFERENCES product (id_product_ext) ON DELETE No Action ON UPDATE No Action;

ALTER TABLE user_product_ext ADD CONSTRAINT "FK_UserProductRolesExt_UserProfile"
    FOREIGN KEY (id_profile) REFERENCES user_profile (id) ON DELETE No Action ON UPDATE No Action;

ALTER TABLE user_roles ADD CONSTRAINT "FK_UserRoles_Role"
    FOREIGN KEY (id_role) REFERENCES role (id) ON DELETE No Action ON UPDATE No Action;

ALTER TABLE user_roles ADD CONSTRAINT "FK_UserRoles_UserProfile"
    FOREIGN KEY (id_profile) REFERENCES user_profile (id) ON DELETE No Action ON UPDATE No Action;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE permission
    IS 'Справочная таблица хранения разрешений';

COMMENT ON COLUMN permission.id
    IS 'Уникальный идентификатор разрешения';

COMMENT ON COLUMN permission.name
    IS 'Имя разрешения';

COMMENT ON COLUMN permission.descr
    IS 'Описание разрешения';

COMMENT ON COLUMN permission.alias
    IS 'Алиас разрешения для enum внутри java кода';

COMMENT ON COLUMN permission.deleted
    IS 'Признак удаленного разрешения (физически строки из таблицы не  удаляем, проставляем этот признак)';

COMMENT ON CONSTRAINT "PK_Permission" ON permission IS 'Первичный ключ';

COMMENT ON CONSTRAINT "UI_Premission_Alias" ON permission IS 'Уникальный ключ для алиаса';

COMMENT ON TABLE product
    IS 'Таблица с описанием продуктов компании. Синхронизировать полностью не будем, наполняется новыми строками, когда какой-то пользователь, имеющий роль в этом продукте, залогинится к нам.';

COMMENT ON COLUMN product.id_product_ext
    IS 'Внешний идентификатор продукта из MyProduct';

COMMENT ON COLUMN product.name
    IS 'Имя продукта';

COMMENT ON COLUMN product.alias
    IS 'Алиас (код) продукта';

COMMENT ON CONSTRAINT "PK_Product" ON product IS 'Первичный ключ';

COMMENT ON TABLE role
    IS 'Справочник ролей в нашем продукте';

COMMENT ON COLUMN role.id
    IS 'Уникальный идентификатор роли';

COMMENT ON COLUMN role.name
    IS 'Имя роли';

COMMENT ON COLUMN role.descr
    IS 'Описание роли';

COMMENT ON COLUMN role.alias
    IS 'Алиас роли для enum в Java';

COMMENT ON COLUMN role.deleted
    IS 'Признак удаленной роли. Строки в таблице не удаляем, помечаем признаком.';

COMMENT ON CONSTRAINT "PK_Role" ON role IS 'первичный ключ';

COMMENT ON CONSTRAINT "UI_Role_Name" ON role IS 'Уникальный ключ на имя роли';

COMMENT ON TABLE role_permissions
    IS 'Разрешения привязанные к роли (внутренней)';

COMMENT ON COLUMN role_permissions.id_rec
    IS 'идентификатор записи, первичный ключ';

COMMENT ON COLUMN role_permissions.id_permission
    IS 'идентификатор разрешения';

COMMENT ON COLUMN role_permissions.b_set
    IS 'флаг установки пермишена';

COMMENT ON COLUMN role_permissions.id_role
    IS 'Идентификатор роли';

COMMENT ON CONSTRAINT "FK_RolePermissions_Permission" ON role_permissions IS 'Внешний ключ на разрешение';

COMMENT ON CONSTRAINT "FK_RolePermissions_Role" ON role_permissions IS 'внешний ключ на роль';

COMMENT ON CONSTRAINT "PK_RolePermissions" ON role_permissions IS 'первичный ключ';

COMMENT ON TABLE user_product_ext
    IS 'связь пользователя с продуктом (эту инфу берем из BeeWorks и MyProduct)';

COMMENT ON COLUMN user_product_ext.id_rec
    IS 'идентификатор записи, первичный ключ';

COMMENT ON COLUMN user_product_ext.id_profile
    IS 'идентификатор пользователя,, внешний ключ';

COMMENT ON COLUMN user_product_ext.id_product_ext
    IS 'Идентификатор продукта, внешний ключ';

COMMENT ON TABLE user_profile
    IS 'Таблица с профилями внутренних пользователей';

COMMENT ON COLUMN user_profile.id
    IS 'Идентификатор пользователя внутренний';

COMMENT ON COLUMN user_profile.id_ext
    IS 'Идентификатор пользователя внешний, табельный номер';

COMMENT ON COLUMN user_profile.full_name
    IS 'Полное имя (ФИО)';

COMMENT ON COLUMN user_profile.login
    IS 'учетная запись, логин из AD';

COMMENT ON COLUMN user_profile.last_login
    IS 'Дата последнего входа в систему';

COMMENT ON COLUMN user_profile.email
    IS 'E-mail пользователя';

COMMENT ON TABLE user_roles
    IS 'Список ролей (внутренних ) для пользователя';

COMMENT ON COLUMN user_roles.id_rec
    IS 'Идентификатор записи, первичный ключ';

COMMENT ON COLUMN user_roles.id_profile
    IS 'Идентификатор профиля, внешний ключ';

COMMENT ON COLUMN user_roles.id_role
    IS 'Идентификтаор внутренней роли, внешний ключ';
